name: Fetch Secret

on:
  pull_request:
    branches:
      - main
    types: [opened, synchronize]

jobs:
  fetch-secret:
    runs-on: ubuntu-latest

    steps:
      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v2
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: us-east-1

      - name: Fetch Secret
        run: aws secretsmanager get-secret-value --secret-id extendd-interview/mohsinsaeed --query SecretString --output text > secret.txt

      - name: Upload Secret Log
        uses: actions/upload-artifact@v2
        with:
          name: secret-log
          path: secret.txt
